version: '3'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"  # Mapea el puerto 5000 del contenedor al puerto 5000 de tu máquina local
    environment:
      FLASK_ENV: development
    volumes:
      - ./backend:/app  # Permite el desarrollo en caliente

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"  # Mapea el puerto 3000 del contenedor al puerto 3000 de tu máquina local
    environment:
      CHOKIDAR_USEPOLLING: "true"  # Necesario para el desarrollo en algunos entornos
    volumes:
      - ./frontend:/app  # Permite el desarrollo en caliente
